# Generated by Django 3.2.7 on 2021-10-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=50)),
                ('cinema_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50)),
                ('movie_genre', models.CharField(max_length=20)),
                ('movies_in_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_movies_list', to='ticket_booking_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.TimeField()),
                ('cinema_show_times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_timings', to='ticket_booking_app.cinema')),
                ('movie_show_times', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_booking_app.movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='located_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking_app.city'),
        ),
        migrations.CreateModel(
            name='BookSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('book_seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking_app.showtime')),
            ],
        ),
    ]
