# Generated by Django 3.2.7 on 2021-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseats',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
