# Generated by Django 3.2.7 on 2021-10-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0002_bookseats_booked_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='located_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_booking_app.city'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movies_in_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_movies_list', to='ticket_booking_app.city'),
        ),
    ]
